### ISSUE TITLE
Transfer to Wikimedia?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-config-wikimedia#1]
Hey,

This is a great start. Would you be OK transferring this to me/@Krinkle so that we can move it into the Wikimedia organisation?

**Comment by jdforrester** [comment]
(Also `npm` package ownership! I'm jdforrester, he's krinkle there.)

**Comment by markelog** [comment]
Donzo, please check it

**Comment by Krinkle** [comment]
@markelog I verified I co-own the npm package. I can't transfer the repo without admin access though. Can you start the transfer to my account? I'll transfer it to @wikimedia from there. That way it'll maintain history, issue tracker and redirect.

**Comment by markelog** [comment]
Request has been sent

**Comment by Krinkle** [comment]
@markelog Completed both transferred. Thanks!
