### ISSUE TITLE
Set max-statements-per-line to 1

### ISSUE THREAD

**Issue by MatmaRex** [wikimedia/eslint-config-wikimedia#111]
We should add a rule like this:

    "max-statements-per-line": [ "error", { "max": 1 } ],

There are very few situations where more than one statement per line might be a good idea (mostly very short callback functions) and I think even such code is just as good when written out over multiple lines.

We adopted this in VisualEditor easily:
* https://gerrit.wikimedia.org/r/c/VisualEditor/VisualEditor/+/470518
* https://gerrit.wikimedia.org/r/c/mediawiki/extensions/VisualEditor/+/470519

**Comment by edg2s** [comment]
Sounds good to me, there are only 21 issues to fix in MW/core
