### ISSUE TITLE
 Disallow calling String/Array/Object methods introduced in ES6 or later in ES5 environments

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#113]
Using ES6 methods in ES5 often breaks IE11 and older Chrome/Firefox.

See https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/463464/

**Comment by jdforrester** [comment]
Assuming we're going down the #109 route, we'll have a matrix of "es5", "es6", "es2017" language sets and "browser", "jquery browser", "node" environments, with aliases called "client" (initially, "es5" + "jquery browser" and "server" ("es6" + "node"). Where will we put the "not-es2017" rules? Both es5 and es6? Will the not-experimental rules go in all three?

**Comment by jdforrester** [comment]
CC @addshore per discussions.

**Comment by edg2s** [comment]
CC @MatmaRex

**Comment by edg2s** [comment]
Instinctively I think each ES version subset should include the "not" rules for all the versions above it, so [es5 + not-es6 + not-es2017], [es6 + not-es2017], [es2017]

**Comment by jdforrester** [comment]
OK, then in practical terms we'll want the "not" rules to be their own files, transcluded into each profile.

**Comment by MatmaRex** [comment]
I'm not sure if we need to disallow the new methods anywhere other than a browser environment? Presumably we can require some reasonably recent Node version instead of writing code carefully to work on old versions, unlike with IE 11. (I don't really have an opinion about this though, and I'm not sure what fancy plans you have for this repo, do what you wish. :) )

**Comment by jdforrester** [comment]
Currently production runs node 6, which means no to es2015 (https://node.green/); they'll move to node 8 at some point, which means no to es2017; _etc._.

**Comment by MatmaRex** [comment]
Does “extends” work with “no-restricted-properties” like that? Is it going
to actually merge the values, instead of overwriting?

-- 
Matma Rex

**Comment by jdforrester** [comment]
I don't know; was going to test.
