### ISSUE TITLE
Tag next major release

### ISSUE THREAD

**Issue by micgro42** [wikimedia/eslint-config-wikimedia#117]
Hi,

it is great to see the new configuration for linting es5/es6 js has landed in master 🙌.
Do you have a timeline for when you plan to make a new official release to npm? We would love to use this updated configuration in the Wikibase extensions.

I assume this next release would be a major version bump due to the changed usage?

**Comment by edg2s** [comment]
Very soon :) we're just ironing out a few issues with regards to the addition of the jQuery plugin.

Yes, will be v0.9.

**Comment by micgro42** [comment]
That is good to hear, I looking forward to it 😊

For future reference the related Wikibase ticket: [T209932: Update mediawiki eslint config](https://phabricator.wikimedia.org/T209932)

**Comment by jdforrester** [comment]
https://github.com/wikimedia/eslint-config-wikimedia/tree/release-0.9.0 for a being-worked-on release.
