### ISSUE TITLE
Add rule to prevent jQuery animations

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#131]
Add `no-animate` and `no-animate-shorthand/shortcut` as proposed in wikimedia/eslint-plugin-jquery#33.

jQuery animations can almost always be replaced by CSS transitions, which are much more performant.

**Comment by edg2s** [comment]
no-fade added by #132

**Comment by Krinkle** [comment]
eslint-plugin-jquery v1.3.2-wmf.5 is now tagged, which unblocks the next step here, I think.
