### ISSUE TITLE
Allow users to use wikimedia/server with later versions of ES

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#134]
Currently wikimedia/server uses ES6. Using `[ "wikimedia/server", "wikimedia/language/es2015" ]` won't work because the not-es2015 rules from es6 won't get removed.

**Comment by Krinkle** [comment]
I call briefly having talked about this use case in one of the issues/PRs around the creation of the client and serve presets. We concluded that when using an ES version requirement different from the minimum we set by default, projects should compose the rules locally from the mixins we provide.

The readme covers this for the case of client-code supporting ES3, and server-code supporting older version of Node.js, but it applies in the other direction as well.

If we can magically make it work, I'd support that, but I worry about the complexity and indirection that would introduce. Ideas?

**Comment by jdforrester** [comment]
Oh, boo, yes. :-(

**Comment by edg2s** [comment]
> projects should compose the rules locally from the mixins we provide.

The problem is there are bunch of rules built in to `server.json` where es6 is loaded. If we separated those out into `server-rules.json` that would be possible.

**Comment by Krinkle** [comment]
@edg2s Hm... the rules currently in there don't seem related to Node.js, though. Looks like they might better fit under language/es6?

**Comment by edg2s** [comment]
Good point, currently the language/ rules are only language feature warnings in the not- prefixed files, but really we should move these rules to es6.json. If someone wanted to target es6 browsers with client+es6 they should expect to get these rules applied.

server.json rules should just be for node specific rules only, which we currently don't have.

Of course if we were to add node specific rules in the future then my point in my previous commend would stand, and we should probably put them in a node.json file, with server.json becoming just a shortcut for node+es6.

**Comment by edg2s** [comment]
> node specific rules only, which we currently don't have.

Actually we have `env: { node: true }`, so that could be moved to node.json

**Comment by jdforrester** [comment]
In person, I proposed that instead of doing this, we should drop the language specification from `wikimedia/server` and have each repo explicitly state their language flavour (_i.e._ `[ 'wikimedia/server', 'wikimedia/language/es2015' ]`). This is a breaking change (oh well) and not lovely for our (relatively few) node repos, but avoids needing another level of abstraction, and lets the node-using repos move pretty quickly but disparately from node6 to node8 to node10 over the next few months.

**Comment by edg2s** [comment]
I think we should keep a default language for our `server`/`client` rules for now. It's definitely the case that client code has a default language (ES5), and I think we should do the same with server code. Users using the default language get a one line extend (`client`/`server`), and users using a different lang will have to extend 3 rulesets, e.g. `common+client+es6` /  `common+node+es2017`. Removing the default languages would mean only 2 rulesets for these edge cases, but also would require 2 rulesets for the default case.

**Comment by jdforrester** [comment]
I suppose.
