### ISSUE TITLE
Use reportUnusedDisableDirectives to get rid of invalid-results.json files

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#135]
Our current approach for checking that a rule is being triggered is to first check that no errors are reported, then in order to check each inline comment correspond to an actual error suppression, we run eslint with `allowInlineConfig` set to false, and compare the results to the `invalid-results.json` file.

I think if we just run our checks with reportUnusedDisableDirectives, then that should effectively provide the same check: that each listed rule is actually suppressing an error.

**Comment by edg2s** [comment]
This will also be a more robust check. Our current approach is prone to error, as made evident by #138

**Comment by jdforrester** [comment]
Interesting idea. I like it.
