### ISSUE TITLE
Consider new-cap rule

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#15]
Looks like we'd need an exception for $.Deferred():

`"new-cap": ["error", { "capIsNewExceptions": ["Deferred"]}]`

If there were many more exceptions in the codebase it may be too hard. Also don't know if that array is concatenated when you override.

**Comment by edg2s** [comment]
we already have this :/

**Comment by Krinkle** [comment]
The the record: 565d290f4c70302c68ff8916f8093e3fc57ef4eb.
