### ISSUE TITLE
Add "es6" env to presets for ES2015 and later

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/eslint-config-wikimedia#151]
When using ESLint out-of-the-box, and setting `parserOptions: es2017`, there will be errors for code uses `Promise`, `WeakMap`, and any other JS interfaces that were introduced in ES6. Despite them obviously being present in ES2017.

This is because the handling for the syntax parser in ESLint is separate from the list of global variables it thinks will exist. The list of global variable is limited by default to just ES5 (decided within ESLint, not in our presets) . So unless `env: es6: true` is set, these always trigger warnings.

I ran into this when using eslint-config-wikimedia in a Node.js service requiring Node 10 or above, with `wikimedia/language/es2017`, and got warnings for using Promise until I added `env: es6`. It felt strange to add "es6" env for es2017 envs.

Upstream at ESLint, I asked about this, and looks like this is intentional. Syntax like `new Promise()` is syntactically valid ES5, it's just that there is no global named Promise by default. You could, however, load es6-shim in your project and then set `env: es6` whilst keeping `parserOptions: es5`.

And inversely, you could use Babel and write code that supports ES6 syntax (compiled), but yet would break if it referenced Promise or WeakMap. E.g. `env: es5` whilst having `parserOptions: es6`.

While Babel transforms ES6 syntax to ES5, it does not replace calls to ES6 interfaces or methods with shims for ES5. So this separation, while perhaps sometimes unexpected, is needed necessary.

Anyway, I'm proposing we:

* Keep `env: es6` in the es6 preset.
* Also add `env: es6` to the es2015-2017 presets.

This would mean that generally presets work out of the box as intended. And, if you're supporting environments older than the syntax you write in but don't want to use their interfaces with polyfills, then you set `env: es6: false`. This will activate the appropriate warnings from `no-undef` for when you accidentally try to use a newer API.

Note that this does not affect `wikimedia/client` (which targets ES5), and does not affect `wikimedia/server` (which targets ES6, and would keep `env: es6` as part of its preset in node.json, even if not in es6.json).

Instead, this issue affects projects using the partial presets for es2015 or above (native, or transpiled).

**Comment by edg2s** [comment]
+1
