### ISSUE TITLE
Prep. for eslint 6?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-config-wikimedia#173]
When sindresorhus/grunt-eslint#162 lands, we'll need to upgrade to target that; do we need to adjust any rules/add anything new? Changes are: https://github.com/eslint/eslint/compare/v5.16.0...v6.0.1

**Comment by edg2s** [comment]
https://github.com/eslint/eslint/releases

**Comment by edg2s** [comment]
Can't see many new rules, just some changes to :recommend:
eslint/eslint/pull/11518

**Comment by edg2s** [comment]
A few rules have been turned on (some of which we already have, so can be removed from our rules).

One rule has been turned off, which we will want to turn on again: `no-console`.

**Comment by jdforrester** [comment]
Kk, if we're dropping rules because they're upstream that will mean that our eslint 6 compat upgrade is not sanely back-compat, so we'll have to make that a breaking change. (Not a big deal, just a reminder to self.)

**Comment by edg2s** [comment]
I'm sure we've done that in the past when `recommended` changed.

**Comment by edg2s** [comment]
We actually already turn on no-console explicitly in `client`. I'm okay with leaving it off in `server` per upstream.

**Comment by edg2s** [comment]
CI failed in Node 6. I assume that means we need to drop Node 6 support?

**Comment by jdforrester** [comment]
> CI failed in Node 6. I assume that means we need to drop Node 6 support?

Yes.
