### ISSUE TITLE
Reconsider prefer-template rule

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#193]
This was introduced in #168, but I'm not sure its a great idea. For long messages where there are lots of variables this template syntax may makes sense, e.g.

`'Hello ${user}, welcome to Wikipedia'`
or
`'<a href="${url}">${label}</a>'`

However the former is handled by our messages system, and the latter should be using DOM building.

More common cases on the server are path concatenations, in which case the extra syntax (`${}`) just makes the code harder to read if anything, compare:

```
__dirname + '/foo/bar'
```
with
```
`${__dirname}/foo/bar`
```

As a developer it is annoying that if I modify the above to remove the `__dirname` prefix, I have to change the string escape system. This also results in less clear diffs:
![image](https://user-images.githubusercontent.com/180672/65043152-42a27700-d952-11e9-9294-113462a4d0de.png)
![image](https://user-images.githubusercontent.com/180672/65043246-72517f00-d952-11e9-8e64-e961aa6f556d.png)

I don't think we should disallow templates, there will be cases with long strings and lots of variables where it makes sense, but I think enforcing this as a rule no matter how short the string is is not an improvement.

**Comment by edg2s** [comment]
CC @Krinkle @jdforrester @niedzielski @jdlrobson

**Comment by jdforrester** [comment]
Hmm, yeah. Maybe we can differentiate between "real" server code (i.e., for services), where they want this rule, and the rest like linter code, where we might want to avoid it?

**Comment by Krinkle** [comment]
I think this is an area where a hard and fast rule might indeed deter readability and overall productivity. There's some things we don't need to enforce and can leave up to author preference, where there is minimal impact (if any) if the "wrong" format is chosen.

That is, I don't think it's particularly harmful to sometimes accidentally have a backticked string without variables, or to accidentally have a long variable-rich message without backticks.

I'd support removal of the rule, but to maintain the social practice that we generally prefer backticks in ES6 code for multi-line strings and/or strings with "many" variables.
