### ISSUE TITLE
Set no-jquery to discourage jQuery and instead expect $ only

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-config-wikimedia#195]
Following wikimedia/eslint-plugin-no-jquery#93, we can set `constructorAliases` to `[ '$' ]` instead of the (new) default of `[ '$', 'jQuery' ]`.

**Comment by Krinkle** [comment]
Sounds good to me. Should generally go hand-in-hand with how a repo already configures `eslintrc/globals` with `$`, or `jQuery`, or both.

**Comment by edg2s** [comment]
I'm not sure. The missing jQuery global is what enforces users not using it, not this plugin. If for some reason jQuery is made available (e.g as in inline exception), then we should lint against bad uses of it.

**Comment by Krinkle** [comment]
Right. I see. I got it backwards. Reducing `constructorAliases` to `$` won't make it stricter by disallowing `jQuery` (like we want), but actually does it opposite by allowing everything to be done with `jQuery`, with our no-jquery rules then only applying to `$`

To enforce disuse of it, `eslintrc/globals` suffices.

**Comment by jdforrester** [comment]
Kk.
