### ISSUE TITLE
valid-jsdoc rule is deprecated

### ISSUE THREAD

**Issue by ricordisamoa** [wikimedia/eslint-config-wikimedia#210]
ESLint team [stated](https://eslint.org/blog/2018/11/jsdoc-end-of-life) they will no longer maintain JSDoc support upstream, suggesting [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) as a replacement.

**Comment by jdforrester** [comment]
Oh, joy. Thanks for letting us know.

**Comment by ricordisamoa** [comment]
To be fair it's already required in a few Services repos https://codesearch.wmflabs.org/search/?q=eslint-plugin-jsdoc&i=nope&files=package%5C.json&repos=
