### ISSUE TITLE
Consider ~~eol-last~~ no-multiple-empty-lines improvements

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#23]
http://eslint.org/docs/rules/eol-last

**Comment by Krinkle** [comment]
LGTM.

We should also consider extending our config for `no-multiple-empty-lines` with `maxEOF: 0` to ensure there is no empty line at the end of a file. http://eslint.org/docs/rules/no-multiple-empty-lines

Note: `maxEOF: 0` passes on `foo\n`. It matches empty lines, not line breaks.

**Comment by edg2s** [comment]
Apparently we already have eol-last, re-purposing this issue for Krinkle's suggestions.
