### ISSUE TITLE
Consider no-array-constructor and no-new-object

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#24]
Blocks `new Array(1,2,3)` (which should be `[1,2,3]`) but not `new Array(length)`

http://eslint.org/docs/rules/no-array-constructor

http://eslint.org/docs/rules/no-new-object

**Comment by Krinkle** [comment]
LGTM. I don't think this is controversial.

It's an implied part of our established code conventions. While omitted for brevity at  https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript, it is considered an anti-pattern. It's typically something JavaScript-beginners might try when looking for something familiar from another programming language.

**Comment by jdforrester** [comment]
SGTM.
