### ISSUE TITLE
Consider node-specific rules

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#245]
See https://eslint.org/docs/rules/callback-return

**Comment by edg2s** [comment]
Similar: https://eslint.org/docs/rules/handle-callback-err

**Comment by jdforrester** [comment]
Hmm. Are we going to hit the false positives often in current code? If not, sure.

**Comment by edg2s** [comment]
Looks like all the node rules are being moved to a plugin. We should consider https://github.com/mysticatea/eslint-plugin-node
