### ISSUE TITLE
Update to ESLint 7.0.0

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#248]
This will be a breaking change obviously, but we already have several breaking changes (new rules) since 0.15.3.

**Comment by edg2s** [comment]
The other thing this does is drop support for Node 8. I don't know if that is significant for any of our products. A service can still execute in Node 8, but only check linting in Node 12. Static analysis does not need to use the same environment as for code execution.

**Comment by jdforrester** [comment]
We don't use node 8 in Wikimedia production anywhere (it's 10 except in a very few places where it's still 6(!)), so I think that's fine. Developers are expected to have better than prod, not worse, locally.

**Comment by edg2s** [comment]
Worst case is some has their CI configured to run tests in Node 8 for compatibility, and tests include linting.
