### ISSUE TITLE
Provide ability to lint YAML

### ISSUE THREAD

**Issue by nikkhn** [wikimedia/eslint-config-wikimedia#317]

**Comment by edg2s** [comment]
Like https://github.com/aminya/eslint-plugin-yaml?

**Comment by jdforrester** [comment]
If we have some Wikimedia-specific common rules to enforce in the YAML files from that plugin, adding a yaml profile with it to Wikimedia's config would be simple enough, sure. I don't have particular opinions on what our YAML files should look like, though. :-)

**Comment by edg2s** [comment]
The plugin above just checks for validity it seems. The JSON plugin does a few additional things like finding duplicate keys. It would be nice if both could do indentation as well.

**Comment by nikkhn** [comment]
Interestingly enough, I wanted to submit this as an idea and then decided against it...and I apparently somehow clicked the "Save" button haha. It actually ended up not being super pertinent to the use case I had in mind, so can close for now since no pressing use :)
