### ISSUE TITLE
eslint config does not lint dot files like .stylelintrc.json/.eslintrc.json

### ISSUE THREAD

**Issue by umherirrender** [wikimedia/eslint-config-wikimedia#374]
Even when eslint is running for `.` it missed the dot files like `.stylelintrc.json`/`.eslintrc.json`

See https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GlobalWatchlist/+/677553

It is possible to change the config `eslint-config-wikimedia` to include also dot files for linting?
Or must be done on each repo?
What must be done to enable dot-file linting?
Or it is not wanted?

**Comment by hashar** [comment]
I had the issue when introducing jsoc and `.jsdoc.json` file improperly formatted with spaces. https://gerrit.wikimedia.org/r/c/mediawiki/tools/api-testing/+/698562/2/.jsdoc.json#2

My fix has been to add a reverse pattern in `.eslintignore`:
```
!.*.json
```

And I guess one might want to extend to add `!.*.js` as well.  Would be nice to have that added to our eslint-config by default.

**Comment by edg2s** [comment]
This is either resolved or a downstream issue. If I add duplicate "rules" keys to the `.eslintrc.json` file in this repo I get an error.

**Comment by jdforrester** [comment]
Per Ed. Please re-open if you can reproduce.
