### ISSUE TITLE
common: Consider rules from eslint-plugin-unicorn

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#378]
[eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) contains some useful rules that haven't made it into eslint core, such as:

* [prefer-date-now](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md)
* [prefer-string-slice](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-slice.md)
* [no-useless-undefined](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-undefined.md)
* [prefer-includes](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-includes.md) (ES6)
* [throw-new-error](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/throw-new-error.md)

and probably many more.

**Comment by Krinkle** [comment]
> * [prefer-string-slice](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-slice.md)

👍  I added this to our [coding conventions](https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript) years ago, and did a few sweeps over the years. The rule would certainly help with on-boarding.

> * [throw-new-error](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/throw-new-error.md)

👍 Seems trivial and narrowly scoped for what seems like could only be a mistake. I note that this is not forbidding use of throwing string literals or the result of differently named functions, e.g. `throw makeFoo()` and `throw "bar";` remain accepted by this rule. It just throws for `throw SomethingError()` without `new`.
