### ISSUE TITLE
Consider qunit/no-assert-ok

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/eslint-config-wikimedia#381]
This is not (yet) part of the upstream "recommended" preset, but something for us to consider opting into early:

https://github.com/platinumazure/eslint-plugin-qunit/blob/v6.2.0/docs/rules/no-assert-ok.md

I wrote [a blog post](https://timotijhof.net/posts/2015/qunit-anti-patterns/) a while ago, in which I also rant about this, and it came up recently in chat following [change 707619 (WikimediaEvents)](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/WikimediaEvents/+/707619).

In a nut shell, `ok()` is loose, and in general one should use a strict assertion instead. Whether simply `strictEquals/true`, or something else if it is not about booleans (e.g. typeof function, isArray, or whatever the expected value may be).

**Comment by edg2s** [comment]
Seems sensible, will require a fair amount of fixing (a shame the rule isn't fixable).

What is going to be the recommended way to assert that a promise resolves? Currently `assert.ok(true,...)` is common. QUnit has `assert.rejects`, but not `assert.resolves`.

**Comment by Krinkle** [comment]
@edg2s

In native async code, I'd actually use the same assertions as for synchronous code by using `await`.

```js
QUnit.test( 'example', async assert => {
    assert.true( await thing() );

    const data = await someThing(); 
    assert.true( data.isFresh );
} );
```

QUnit checks for you that test closures don't throw, and also that any returned promise resolves (native async functions return promises when called). Although async-await is new in ES2017, we could adopt this in ES5/ES6 codebases today, if you don't mind two compats in one repo. Evergreen browsers that we develop with and run unit tests in support this natively. We'd extend `wikimedia/language/es2017` for the `tests/` directory, like how we extend `wikimedia/qunit` already.

When using promises, I believe we usually return to the test function:

```js
QUnit.test( 'example', function ( assert ) {
    return someThing().then( function ( data ) {
        assert.true( data.isFresh );
    } );
} );

QUnit.test( 'example', function ( assert ) {
    return someThing().then( function ( data ) {
        assert.true( data.isFresh );
    } ).then( function () {

        return otherThing();
    } ).then( function ( data ) {
        assert.false( data.isFresh );
    } );
} );
```

This style might feel messy when doing multiple within one test case though. You can use `assert.async()` to treat each portion separately (and concurrently):

```js
QUnit.test( 'example', function ( assert ) {
    someThing().then( function ( data ) {
        assert.true( data.isFresh );
    } ).then( assert.async() );

    otherThing().then( function ( data ) {
        assert.false( data.isFresh );
    } ).then( assert.async() );
} );

QUnit.test( 'example', function ( assert ) {
    var someDone = assert.async();
    someThing().then( function ( data ) {
        assert.true( data.isFresh );
        someDone();
    } );

    var otherDone = assert.async();
    otherThing().then( function ( data ) {
        assert.false( data.isFresh );
        otherDone();
    } );
} );
```
