### ISSUE TITLE
Add tests for disallow rules

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/eslint-config-wikimedia#5]
(From comments in #3)

While we have a test fixture that ensures our coding style is not rejected, disabling all rules would still make that pass. We need another test that asserts certain failures would happen when requirements are not met.

This will need to be more than a simple fixture since it's important to assert how many errors were triggered, which ones, and where. ESLint has a Node API that we can use for this.

**Comment by edg2s** [comment]
We could create a failing file with `/* eslint-disable-line */` fixes. We can test it passes normally, then test it fails N times when all the comments are stripped (where N is the number of -disable-line comments). That way the file would be fairly self-documenting.
