### ISSUE TITLE
Review new rules in eslint 4.0.0

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#59]
As of v4.0.0-beta.0 the following new rules look useful:

switch-colon-spacing: https://github.com/eslint/eslint/commit/482d5720c7faee174b192b2a131ec5ab93ceff3c

for-direction: https://github.com/eslint/eslint/commit/0ef09ea071f7df0cfb3f76ddea9ad746cb619912

**Comment by Krinkle** [comment]
* <http://eslint.org/docs/rules/switch-colon-spacing>
* <http://eslint.org/docs/rules/for-direction>

Yep. LGTM, to both.

**Comment by jdforrester** [comment]
We'll bump the (minor because we're < 0) version when we do this.

**Comment by edg2s** [comment]
We should also add `"semi-style": [ "error", "last" ]`

**Comment by jdforrester** [comment]
Can we declare this resolved?
