### ISSUE TITLE
Consider arrow-parens

### ISSUE THREAD

**Issue by Nikerabbit** [wikimedia/eslint-config-wikimedia#61]
I started reviewing some ES6 JavaScript code and the various different ways to use parenthesis with arrow functions caught my eye. Would be nice to see if there is a consensus for some style and enforce that automatically.

<https://eslint.org/docs/rules/arrow-parens>

**Comment by edg2s** [comment]
Is there an emerging consensus in our current codebase? "always" looks like the most legible option to me...

**Comment by Nikerabbit** [comment]
CXServer mostly uses parentheses with a handful of exceptions.

**Comment by jdforrester** [comment]
Do we want to start putting ES6 code rules into this set? Right now it's ES5-focussed (because it's principally for client-side code).

**Comment by edg2s** [comment]
Unless there is a serious performance impact, it should be okay to keep them together. WMF projects have a reasonable amount of ES6 code knocking around as build scripts, micro-services, and even client side code that is transpiled (hover cards?). Unlike the qunit rules there shouldn't be a problem merging these (at least I haven't seen any problems yet).
