### ISSUE TITLE
Consider adding no-prototype-builtins rule

### ISSUE THREAD

**Issue by mooeypoo** [wikimedia/eslint-config-wikimedia#64]
This seems to be more than "just" stylistically relevant, it's also good for avoiding potentially bad code errors, especially when done with queries or objects that come from sources that can't be completely trusted to have "clean" properties.

Forcing this:
`var hasBarProperty = foo.hasOwnProperty("bar");`

To be this:
`var hasBarProperty = Object.prototype.hasOwnProperty.call(foo, "bar");`

https://eslint.org/docs/rules/no-prototype-builtins

**Comment by jdforrester** [comment]
@Krinkle, @edg2s, @MatmaRex – thoughts?

**Comment by MatmaRex** [comment]
Sure, seems harmless. I don't really care either way.

**Comment by Krinkle** [comment]
LGTM!

**Comment by Krinkle** [comment]
Looks good to me!
