### ISSUE TITLE
Consider new-parens rule

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/eslint-config-wikimedia#7]
http://eslint.org/docs/rules/new-parens

Consider enabling the `new-parens` rule. This would require `new Date` to be written as `new Date()`.

We've not previously expressed this in coding conventions, though in most code we include parenthesis.

/cc @wikimedia/code-conventions

**Comment by edg2s** [comment]
I've never seen this rule not being followed (deliberately), so seems sensible.

**Comment by jdforrester** [comment]
Agreed.
