### ISSUE TITLE
Consider no-lonely-if rule

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/eslint-config-wikimedia#8]
http://eslint.org/docs/rules/no-lonely-if

We don't currently express this explicitly in our coding conventions, but I've never seen this used intentionally and would be nice to avoid. Thoughts?

Disallow:

``` js
} else {
    if (bar) {
        // ...
    }
}
```

Require:

``` js
} else if (bar) {
    // ...
}
```

/cc @wikimedia/code-conventions

**Comment by jdforrester** [comment]
Seems sensible to me.

**Comment by edg2s** [comment]
shall we test it against VE+OOUI and see if it throws up anything?

**Comment by edg2s** [comment]
So the rule flags cases such as:

```
if ( x ) {
 // x
} else {
  if (y) {
    // !x && y
  } else {
    // !x && !y
  }
}
```

I think when the 'lonely' if has an else, it is clearer to write in this nested way, than as a flat `if`/`elseif`/`else`. Especially if the x=true case is later split further.
