### ISSUE TITLE
Enable no-debugger and no-console

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#9]
Both of these were enabled previously in jscs/jslint. Some projects (dev tools) might want to disable no-console.

**Comment by Krinkle** [comment]
Yep. It's enabled in `eslint:recommended` as well. Most simple node programs that don't use an output library will probably want to keep using console.log() directly, but it's easy enough to override in eslintrc - which we would've done in jshintrc as well.
