### ISSUE TITLE
Consider relaxing one-var for let and const

### ISSUE THREAD

**Issue by ricordisamoa** [wikimedia/eslint-config-wikimedia#96]
The `one-var` rule is currently set to `[ "error", "always" ]` requiring variables to be declared in single statements at the top of their respective scope.

However, as the [ESLint documentation](https://eslint.org/docs/rules/one-var) puts it,
> The single-declaration school of thought is based in pre-ECMAScript 6 behaviors, where there was no such thing as block scope, only function scope. Since all `var` statements are hoisted to the top of the function anyway, some believe that declaring all variables in a single declaration at the top of the function removes confusion around scoping rules.

In the following example it would make sense to combine `var a, c` at the top of the function scope, but that is hardly the case with `let`.

```javascript
function () {
	// `a` and `c` are `undefined` here
	// accessing `b`, `d` or `e` here would throw a ReferenceError

	var a;
	let b;

	// `a`, `b` and `c` are `undefined` here
	// accessing `d` or `e` here would throw a ReferenceError

	if ( condition ) {
		var c;
		let d;
	}

	// `a`, `b` and `c` are `undefined` here
	// accessing `d` or `e` here would throw a ReferenceError

	let e;

	// `a`, `b`, `c` and `e` are `undefined` here
	// accessing `d` here would throw a ReferenceError
}
```

The same applies to `const` declarations as well.

Block scoping and [Temporal Dead Zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_Dead_Zone) make it both sensible and convenient to declare variables just before use, mistakes being easily caught by ESLint's own [`no-undef`](https://eslint.org/docs/rules/no-undef) and [`no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define). Why would ECMAScript 2015+ code have to trade Wikimedia style compliance for readability?

Something like `[ "error", { "var": "always", "let": "consecutive", "const": "consecutive" } ]` could be used to enforce consistency, e.g. `let a, b` in place of `let a; let b`. Alternatively, the latter form may be made admissible or even mandatory.

**Comment by jdforrester** [comment]
With the services sub-config (#97) we'll be enforcing const/let over var and never-ing `one-var`; that would fix this for you, albeit in a preset designed for back-end services rather than front-end code.

**Comment by ricordisamoa** [comment]
Thank you @jdforrester. However, it looks like that config will also have a lot of unrelated differences.

**Comment by jdforrester** [comment]
@ricordisamoa Now that that is merged, with a lot fewer changes, does https://github.com/wikimedia/eslint-config-wikimedia/blob/master/server.json do what you'll need here?

**Comment by ricordisamoa** [comment]
@jdforrester That's a step in the right direction. It should be only a matter of time until more daring projects start using those rules paving the way for a truly client-side ES6 preset :wink:
